### ISSUE TITLE
홈페이지 하단에 편지 공개에 동의하지 않을 경우를 대비한 법률적 공유 동의 여부 고지

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#10]
## 온라인 상 또는 서면으로 보내주신 기증편지 또는 감사편지는 SNS 및 웹사이트에 공개될 수 있습니다. 공개를 원치 않으시는 경우 이메일 또는 전화를 통해 알려주시면 공개하지 않겠으며, 이미 공개된 경우라면 SNS 및 웹사이트에서 삭제하겠습니다.  

혹시 본인의 편지 공개에 동의하지 않을 경우를 대비해 법률자문 받은 내용입니다. 첫 페이지 하단에 보이도록 들어가야 할 것 같습니다. 서면 편지지 하단에도 고지할 예정인데, 이야기옷장 하단에 한번 더 고지하면 좋을 거 같습니다.

**Comment by keedi** [comment]
진행합니다. 관련해서 갱신된 내용이 있다면 추가 바랍니다. :)

**Comment by keedi** [comment]
첫 페이지의 어디쯤 어느 정도의 크기로 들어갔으면 하는지 확인 부탁드립니다.

이미지 편집 프로그램으로 화면 캡쳐후 간단하게 크기를 고려해서 표시해주시면 참고해서 진행하겠습니다.

**Comment by pingpongworks** [comment]
[프레젠테이션1.pdf](https://github.com/opencloset/OpenCloset-Story-Web/files/223178/1.pdf)
첫 페이지 맨 아래 하단에 첨부이미지와 같이 "컨텐츠 관리고지"라고 제목을 붙여서 넣으면 좋겠습니다.

**Comment by keedi** [comment]
처리한 화면입니다.

![screenshot-monster silex kr 10305 2016-04-18 16-59-32](https://cloud.githubusercontent.com/assets/138451/14597352/1aacbd0c-0587-11e6-8a2e-4ab946ffa11d.png)

**Comment by keedi** [comment]
작업 완료했습니다. 릴리스 대기중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

문제없는지 확인해주시고 문제 없다면 확인요망 라벨 제거 부탁드립니다. :)

디자인적 이슈나 소소한 수정사항이 있으시다면 라벨 제거하신 후 현재 이슈를 얼어주시고(지금 닫혀있으니) 그대로 커멘트 달아주시면 됩니다.
