### ISSUE TITLE
기증이야기, 대여이야기 하단에서 아래로 페이지 스크롤이 안됨

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#13]
모바일에서는 잘 되는데,
컴퓨터에서는 아래로 더 열리지를 않네요.

**Comment by keedi** [comment]
흠 여전히 발생하고 있나요? 저는 아직까지 재현이 안되는데... 재현되는 장비가 있다면 자세한 사양이라던가 운영체제 및 브라우저 버전도 같이 알려주세요. 발생할 때 바로 알려주시면 가장 좋습니다.

**Comment by pingpongworks** [comment]
아, 아래로 스크롤 잘 되고 있습니다~

**Comment by pingpongworks** [comment]
그런데, 확인요망을 확인했기 때문에 
확인요망 위에 있는 LABEL을 클릭하려고 하니까 클릭이 아예 안 되네요.
만일이한테 물어보니까 키디님이 권한을 주셔야한다고 하네요~

**Comment by yongbin** [comment]
@pingpongworks  Github 열린옷장 맴버와 dev(개발) 팀 맴버추가 초대장을 보냈습니다. 수락해주신뒤에 한번 더 시도해보시기 바랍니다.

![screen shot 2016-04-22 at 12 06 16 pm](https://cloud.githubusercontent.com/assets/52704/14730577/bf6267fe-0882-11e6-8b37-6fdd5221b1d5.png)

**Comment by keedi** [comment]
재현되지 않는 이슈므로 일단 invalid로 수정하고 이슈 닫습니다.
