### ISSUE TITLE
열린옷장 기증메시지 입력완료

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#15]
열린옷장 기증의류에 대한 열린옷장의 기증메시지를 정리해서 프로그램에 입력해놓았습니다. 이제부터 열린옷장 옷으로 대여하신 분들이 이야기옷장에서 공란이 아닌 메시지를 보실 수 있습니다^^

**Comment by 10001if** [comment]
@keedi 열린옷장은 따로 메세지를 입력하지 않아도 디폴트로 메세지 내용이 입력되게 할 수 있나요? 전에 이 부분 관련해서 고민해 주셨던 것 같은 기억이 나서요~

**Comment by keedi** [comment]
@10001if #27 항목에서 해당사항은 이야기를 나누죠.

**Comment by keedi** [comment]
본 항목은 이슈가 아니므로 닫겠습니다. :)
