### ISSUE TITLE
첫 페이지 열린옷장 소개 수정 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#2]
![1](https://cloud.githubusercontent.com/assets/17288038/13104038/0e719076-d59e-11e5-8d1b-71545d6cca19.png)
어제 말씀드린 몇 가지 여기에도 정리해둘게요~

# 옷장을 열다
열린옷장은 옷장 속에 잠들어있는 정장을 기증받아, 꼭 필요한 분들과 함께 공유합니다. 옷과 함께 옷에 담긴 이야기까지 공유하여 사람과 사람이 더 가까워지고 소통할 수 있는 세상을 꿈꾸고 있습니다. 
특히 열린옷장은 요즘 취업 때문에 고통 받는 청년구직자들을 응원합니다. 면접을 앞둔 청년들에게 사회선배들의 경험과 응원이 담긴 정장을 전달하여 면접 복장에 대한 부담을 덜어주고자 합니다. 기증과 공유를 통해 모두가 함께 만든 세상에서 가장 커다란 옷장! 열린옷장은 꿈꿉니다. 이 옷장을 통해 ‘누구나 멋질 권리’를 누리기를! 누구에게나 도전의 기회가 활짝 열리기를! 모두를 위한 공유옷장, 함께 만들어주실 거죠?

**Comment by keedi** [comment]
진행합니다. 관련해서 갱신된 내용이 있다면 추가 바랍니다. :)

**Comment by pingpongworks** [comment]
없습니다. 감사합니다^^

**Comment by keedi** [comment]
작업 완료했습니다. 릴리스 대기중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

문제없는지 확인해주시고 문제 없다면 **확인요망** 라벨 제거 부탁드립니다. :)
