### ISSUE TITLE
푸터의 링크에 GitHub 링크 노출

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#25]
열린옷장 Github가 이야기옷장 하단에 노출되어 있네요. 이유가 궁금합니다~

![default](https://cloud.githubusercontent.com/assets/17288038/14630151/b010f7ea-0646-11e6-8b04-d6743c280642.JPG)

**Comment by keedi** [comment]
Connect 부분은 관계망 관련 링크를 넣어두었는데 깃헙 역시 보통 오픈소스 프로젝트면 링크를 같이 표기하곤합니다. 열린옷장 작업 결과물을 오픈소스로 처리하고 있는 관계로 링크 역시 같이 두었습니다. 물론 링크 여부랑 별개로 이미 이슈나 저장소 등은 공개인 상태입니다.

**Comment by pingpongworks** [comment]
아, 그렇군요^^ 업무대화가 외부에 노출되는게 익숙하지않아서 좀 낯서네요 ㅎㅎ 제가 익숙해져야겠습니다^^

**Comment by keedi** [comment]
현재 말씀처럼 이슈는 아무나(로그인 하지 않은 일면식의 사용자라도) 가능합니다. 따라서 개인정보가 포함되거나 웹주소가 포함되거나 또는 내부적으로 논의해야할 민감한 사항은 올리지 않도록 조심하셔야 합니다. 대부분 기술적이거나 디자인적인 이슈라 공개 페이지라도 크게 문제되지는 않습니다. 물론 저희도 결제하거나 서버 운영과 관련된 부분은 민감한 부분이라 이쪽에 기록하지 않고 별도 공간을 이용하고 있어요.

@10001if 님께서 https://github.com/opencloset/Solving/issues 이라는 저장소를 만드셨던데 이것은 비공개기 때문에 등록된 사용자 이외에는 열람을 할 수 없습니다. 관련해서 해당 저장소의 이슈를 어떻게 쓸지 등은 @10001if 님과 논의 하시면 될 것 같아요.

별거 아니라 조금 쓰시다 보면 금방 익숙해지실 거에요~ :)
