### ISSUE TITLE
열린옷장 기증 메시지가 너무 많이 노출됨

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#28]
![default](https://cloud.githubusercontent.com/assets/17288038/15322125/aabf853c-1c75-11e6-91c9-61bf717a58c8.JPG)
열린옷장 구매의류를 등록할 때마다 열린옷장 기증메시지를 입력하다보니, 보시는바와 같이 기증이야기 페이지에 열린옷장의 같은 메시지가 반복해서 너무 많이 보입니다. 기증페이지에 열린옷장 기증메시지가 보이지 않게 하는 방법 없을까요?

**Comment by keedi** [comment]
@10001if 확인해보시고 여전히 동일한 생각이신지, 아니면 별도 아이디어가 있으신지 말씀해주세요.

**Comment by 10001if** [comment]
@pingpongworks 월요일에 출근하시면 같이 이야기 나눠보시죠~

**Comment by 10001if** [comment]
@pingpongworks 본 이슈에 대해 논의한 결과, 열린옷장 이름으로 기증행위가 발생하는 경우는 일시적이므로 현재와 같이 열린옷장의 이름으로 기증메세지가 반복적으로 올라가는 것에 문제가 없다고 판단하였습니다. 따라서 본 이슈는 닫도록 하겠습니다. @keedi
