### ISSUE TITLE
첫 페이지의 이야기 옷장 읽는 방법 내용 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#3]
<img width="550" alt="2" src="https://cloud.githubusercontent.com/assets/17288038/13104099/7a4ebcec-d59e-11e5-9506-acdd4dba7ed3.png">

# 기증자 
내 이름을 검색하여 옷과 함께 보냈던 ‘나의 정장 기증 이야기’를 찾아보세요. 나에게 도착한 대여자의 
감사편지도 만날 수 있습니다. 

# 대여자
내 이름을 검색하여 내가 기증자에게 보냈던 ‘나의 정장대여 이야기’를 찾아보세요. 내가 대여했던 의류의 기증자와 기증이야기도 만날 수 있습니다.

# 누구나
열린옷장의 기증자와 대여자들이 옷을 통해 나눈 수많은 이야기들을 읽어보세요.  옷깃을 스치며 만들어진 놀라운 사연들을 만날 수 있습니다.

**Comment by keedi** [comment]
진행합니다. 관련해서 갱신된 내용이 있다면 추가 바랍니다. :)

**Comment by keedi** [comment]
작업 완료했습니다. 릴리스 대기중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

문제없는지 확인해주시고 문제 없다면 **확인요망** 라벨 제거 부탁드립니다. :)
