### ISSUE TITLE
매년 12월 말, 기증자에게 그동안 모인 대여자의 편지를 발송하려고 합니다

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#31]
일전에 말씀드린 대로 그동안 모인 대여자의 감사편지를 기증자에게 전달할 방법이 필요합니다.

그래서 '대여자가 기증자에게 보내는 감사편지 읽기' 페이지를 리뉴얼해서 
12월 20일 경에 기증자에게 그 페이지 url을 연하장과 함께 발송하면 어떨까 합니다.

현재는 이렇게 보입니다. 계속 스크롤해서 하나씩 보아야하기 때문에 번거롭습니다.
https://story.theopencloset.net/letters/d/5/o

이렇게 리뉴얼하면 어떨까 합니다. 제가 생각하는 대략적인 스케치입니다. 
![- -](https://cloud.githubusercontent.com/assets/17288038/19379929/8f80f6a4-922f-11e6-9f58-2e4bc6f36328.jpg)

자세한 내용은 다음주에 한번 얼굴뵙고 말씀드릴게요~
github 너무 오랜만에 들어와서 제대로 포스팅된건지도 모르겠네요^^

**Comment by keedi** [comment]
#33 항목에서 처리합니다.

이슈 닫습니다.
