### ISSUE TITLE
노란 편지지가 사라졌어요!

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#32]
![default](https://cloud.githubusercontent.com/assets/17288038/19634086/e0de0a58-99f2-11e6-93b9-4b23c3009708.JPG)

버그인 걸까요? 확인부탁드려요~

**Comment by keedi** [comment]
인터넷 공유기나, 네트워크 망의 지연으로 발생한 문제로 사료됩니다. 특별히 손 댄 것은 없으며, 현재는 잘 나오고 있습니다. 이슈 닫습니다.
