### ISSUE TITLE
뉴스 레터에 첨부할 기증 리포트 페이지 구현

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#33]
1> 검색창에 기증자 본인의 성명을 검색 / 동명이인이 많을 경우, 전화번호로 다시 한번 검색한다거나 해서 본인을 찾습니다.

2> 상단에 '본인의 기증총량'에 대한 리포트가 간략하게 뜨고, 본인의 기증편지가 합께 뜹니다.
      기증편지에는 기증일이 함께 보여, 여러 개일 경우 구분할 수 있도록 합니다.
![-4](https://cloud.githubusercontent.com/assets/17288038/19634681/150da77a-99f8-11e6-84ff-f46fbe425fb8.jpg)

3>기증편지 중 하나를 더 읽기하면, 다음과 같이 각 기증에 대한 기증리포트와 도착한 감사편지를 읽을 수 있도록 합니다.
![-5](https://cloud.githubusercontent.com/assets/17288038/19634774/9c548280-99f8-11e6-9416-faf24ca06c62.jpg)

**Comment by 10001if** [comment]
@keedi 이슈 진행되실 때 불러주시면 제가 설명드리도록 하겠습니다.

**Comment by keedi** [comment]
12월 20일 뉴스 레터 발송 전에 작업이 완료되어야 한다고 합니다.

**Comment by keedi** [comment]
개인정보 보호를 위해 이름으로 검색할 경우 전화번호는 가운데 4자리를 가리고, 이메일은 처음 두 글자를 가리기로 했습니다.

**Comment by keedi** [comment]
마감일이 얼마 남지 않았으므로 진행합니다.

**Comment by keedi** [comment]
기존 페이지를 활용해서 구현할 수는 없고 별도의 페이지로 처리중입니다. 이는 기존 페이지의 경우 검색을 시도하면 기증 건 별로 검색 결과를 보여주는데 반해 현재 리포트 페이지의 경우 검색 이후 기증자 별로 검색 결과를 열람하기를 원하기 때문입니다.

어찌됐든 결론적으로 검색 후 기증 건이 7개가 검색되었지만 이중 2건은 A, 3건은 B라는 동일한 기증자의 기증이라면 검색 결과는 7개가 아닌 4개가 나오게 됩니다.

**Comment by keedi** [comment]
구현 완료한 화면은 다음과 같습니다.

다음은 기증자 검색 화면입니다.
![screenshot-monster silex kr 10305-2016-12-20-16-30-02](https://cloud.githubusercontent.com/assets/138451/21341843/f76bbb6a-c6d1-11e6-8a8e-8a324ba5456f.png)

다음은 특정 기증자 보고서 화면입니다.
![screenshot-monster silex kr 10305-2016-12-20-16-30-51](https://cloud.githubusercontent.com/assets/138451/21341848/fd4f12a2-c6d1-11e6-9874-4f021c288423.png)

다음은 특정 기증자의 특정 보고서 화면입니다.
![screenshot-monster silex kr 10305-2016-12-20-16-31-21](https://cloud.githubusercontent.com/assets/138451/21341854/031b0e20-c6d2-11e6-91e9-0f687d4c8176.png)

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.
