### ISSUE TITLE
기증 메세지가 없어도 열람이 가능하게 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Story-Web#34]
현재는 기증 메세지가 입력되어 있지 않으면 기증자의 기증의류를 대여한 대여자의 메세지를 볼 수 없습니다. 하지만 기증메세지가 입력되지 않더라도 대여자의 메세지를 볼 수 있도록 수정 요청드립니다. 본 이슈는 https://github.com/opencloset/OpenCloset-Story-Web/issues/33 이슈가 해결되는 시점과 함께 준비되어야 합니다. @keedi 바쁘시겠지만 함께 요청드립니다.

**Comment by keedi** [comment]
#33과 함께라기 보다는 #33보다 먼저 해결되어야 하는 이슈 입니다.

**Comment by keedi** [comment]
처리 했습니다.

구현 전 화면은 다음과 같습니다.
![screenshot-monster silex kr 10305-2016-12-19-17-59-54](https://cloud.githubusercontent.com/assets/138451/21306701/bb48f5f6-c615-11e6-90b4-489acc998f37.png)

구현 후 화면은 다음과 같습니다.
![screenshot-monster silex kr 10305-2016-12-19-18-00-03](https://cloud.githubusercontent.com/assets/138451/21306710/bf5a6454-c615-11e6-8b6d-b1ff27db9026.png)

중간 중간 기증 메시지가 없는 항목이 보임을 알 수 있습니다.

**Comment by keedi** [comment]
@10001if 
다만 첫 화면의 메시지 개수를 측량할 때는 메시지가 없는 경우는 세지 않습니다. 관련해서 수정이 필요하다면 별도의 이슈를 열어서 문제를 제기해주세요.

![screenshot-monster silex kr 10305-2016-12-19-18-06-17](https://cloud.githubusercontent.com/assets/138451/21306771/02645ffc-c616-11e6-9544-1bda68b412d5.png)

**Comment by keedi** [comment]
작업 완료했습니다. 이슈 닫습니다. :-)

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.
