### ISSUE TITLE
'000님에게 드리는 감사 더 읽기' 버튼 문자열 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Story-Web#38]
'000님에게 드리는 감사 더 읽기' 

멘트를 

'000님의 기증정장 대여목록 보기'

로 수정 요청드립니다.

본 정보는 기증 리포트 페이지에 나타나는 내용입니다.

![2016-12-20 6 13 48](https://cloud.githubusercontent.com/assets/4696328/21344651/2e7c44d6-c6e0-11e6-88ca-463a69c2a7a0.png)

**Comment by keedi** [comment]
작업 완료했습니다.

![screenshot-monster silex kr 10305-2016-12-20-19-02-38](https://cloud.githubusercontent.com/assets/138451/21346274/0471cdf8-c6e7-11e6-8cf6-bc0e05119f84.png)

**Comment by keedi** [comment]
이슈 닫습니다.
