### ISSUE TITLE
기증리포트 타이틀 위 기증자 성함에 '님'자를 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Story-Web#39]
![2016-12-20 6 13 28](https://cloud.githubusercontent.com/assets/4696328/21344677/518f9a7c-c6e0-11e6-8f88-9a9711f985c0.png)
기증리포트 타이틀 위 기증자 성함에 '님'자의 추가를 요청드립니다.

**Comment by keedi** [comment]
작업 완료했습니다.

![screenshot-monster silex kr 10305-2016-12-20-18-58-14](https://cloud.githubusercontent.com/assets/138451/21346132/53a44d5c-c6e6-11e6-95db-5d50e2fdd18d.png)

**Comment by keedi** [comment]
이슈 닫습니다.
