### ISSUE TITLE
대여 이야기에서 기증 이야기로 이동하는 링크 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#4]
![3](https://cloud.githubusercontent.com/assets/17288038/13104148/b483db18-d59e-11e5-8da6-be41c76313d4.png)

**Comment by keedi** [comment]
진행합니다. 관련해서 갱신된 내용이 있다면 추가 바랍니다. :)

**Comment by keedi** [comment]
#7 에서 언급한 내용과 비슷한 이슈입니다. 이곳도 #5 와는 달리 "님에게"라고 사용하고 있는데 접미사를 "에게"를 사용할지 "께"를 사용하실지 정확하게 확인 부탁드립니다.

**Comment by pingpongworks** [comment]
'에게'로 통일하겠습니다^^

**Comment by keedi** [comment]
작업 완료했습니다. 릴리스 대기중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

문제없는지 확인해주시고 문제 없다면 **확인요망** 라벨 제거 부탁드립니다. :)

디자인적 이슈나 소소한 수정사항이 있으시다면 라벨 제거하신 후 현재 이슈를 얼어주시고(지금 닫혀있으니) 그대로 커멘트 달아주시면 됩니다.
