### ISSUE TITLE
페이지 하단의 전화번호 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Story-Web#43]
현재는 070-4325-**** 로 되어 있는데, 이 번호를 02-6929-1020으로 수정요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1138

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

이슈 닫습니다.

**Comment by keedi** [comment]
@aanoaa wrote:

> `OpenCloset::Plugin::Helpers::footer` 와 `opencloset.css` 를 함께 사용하시면
> 
> https://donation.theopencloset.net/ 의 footer 와 같은 결과를 얻을 수 있습니다.
> 
> 참고
> 
> - https://github.com/opencloset/OpenCloset-Plugin-Helpers/blob/develop/lib/OpenCloset/Plugin/Helpers.pm#L195
> - https://github.com/opencloset/opencloset.css/blob/master/dist/css/opencloset.css#L66


관련해서는 해당 공통 푸터를 사용할 지 아예 sms 매크로 수정 기능처럼 열린옷장이 직접 수정하게끔 할지 고민중입니다. 조만간 푸터 수정 이슈가 한 번 더 있으면 그 때 별도 이슈로 처리하겠습니다.
