### ISSUE TITLE
푸터의 온라인 예약 링크 주소를 변경함

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/OpenCloset-Story-Web#48]
footer에 위치한 '온라인 예약'에 걸린 링크가 online.theopencloset.net으로 되어 있습니다. share.theopencloset.net/welcome으로 변경되어야 합니다.

share.theopencloset.net의 footer도 마찬가지입니다.

**Comment by aanoaa** [comment]
story의 footer 와 share, volunteer, donation 의 footer 는 따로 관리됩니다.

share, volunteer, donation 에서의 링크는 제가 수정하도록 하겠습니다.

**Comment by keedi** [comment]
수정했습니다. 이슈 닫습니다.

**Comment by keedi** [comment]
0.007 버전 릴리스 했습니다. 배포 대기 중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료 했습니다.

**Comment by 10001if** [comment]
@keedi 감사합니다.
