### ISSUE TITLE
기증 이야기에서 대여 이야기로 이동하는 링크 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#5]
![4](https://cloud.githubusercontent.com/assets/17288038/13104167/d539144a-d59e-11e5-990e-186aa552c374.png)

**Comment by keedi** [comment]
진행합니다. 관련해서 갱신된 내용이 있다면 추가 바랍니다. :)

**Comment by pingpongworks** [comment]
아, 이게 실수네요^^ 대여자, 기증자 모두 ''에게'로 통일해주세요~

**Comment by keedi** [comment]
작업 완료했습니다. 릴리스 대기중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

문제없는지 확인해주시고 문제 없다면 **확인요망** 라벨 제거 부탁드립니다. :)

디자인적 이슈나 소소한 수정사항이 있으시다면 라벨 제거하신 후 현재 이슈를 얼어주시고(지금 닫혀있으니) 그대로 커멘트 달아주시면 됩니다.
