### ISSUE TITLE
비공개 편지 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#53]
![2017_ 204_ 2017_ 20 203_19_39 20scannable 20](https://cloud.githubusercontent.com/assets/17288038/25081245/2dd68f54-2384-11e7-8773-ee299fa9c8c5.png)
![2017_ 204_ 2017_ 20 203_38_59 20scannable 20](https://cloud.githubusercontent.com/assets/17288038/25081246/2dd87c74-2384-11e7-8749-a4b80c5f8505.png)

작년말부터 기증편지와 대여편지 하단에 공개동의 체크박스를 만들어 반응을 지켜보았습니다. 
* 기증편지 체크박스 - 공개를 원하지 않음
* 대여편지 체크박스 - 편지공개 동의안함 / 공개는 동의하나 익명을 원함 / 기증자에게만 전달 원함

그런데 생각보다 많은 분들이 체크를 해주고 계셔서 편지 입력을 어떻게 하면 좋을지 정리하고 결정해봐야할 것 같습니다.  익명 관련해서 #11 에서 예전에 이야기된바와 같이 편지를 입력할 때 대여자가 원하는 대로 선택해서 입력될 수 있는 기능이 있으면 좋을 것 같습니다. 

 현재 제 생각으로는, 
* 편지공개 동의 안함  - 입력을 해도 스토리웹에 아예 보이지 않게
* 공개는 동의하나 익명을 원함 - 입력을 하면 편지내용은 보이되, 스토리웹에 대여자 성명은 익명으로 보이게
* 기증자에게만 전달 원함 - 입력을 해도 스토리웹에는 보이지 않고, 연말에 기증자에게만 전달되도록 
이렇게 될 수 있으면 가장 좋을 것같습니다만, 너무 복잡할지 어떨지의견을 듣고 싶습니다. 
@keedi @10001if  내일 오시면 잠깐 이야기나눌 수 있으면 좋겠습니다~

**Comment by 10001if** [comment]
@pingpongworks 정책이 결정되면 @keedi께 요청드려 기능 추가를 요청드리면 될 것 같습니다. 다만, 기증자, 대여자 메세지 관련해서 드는 생각은 마치 설문조사 문항이 어떻게 되느냐에 따라 답변이 달라진다는 느낌이 듭니다. 특히 `편지공개 동의안함`의 경우에는 이런 항목이 존재할 때와 존재하지 않을때의 결과에 대해 생각해 볼 필요가 있을 것 같습니다. 물론, 익명의 경우에는 개인정보에 해당될 소지가 있기 때문에 익명을 원하는 사람에게는 그 이름을 보이지 않게 할 필요가 있을 것 같습니다. 하지만 `편지공개 동의 안함`과 `기증자에게만 전달 원함`의 경우 이 항목을 다르게 표현하는 것이 좋을지 아니면 정말 필요한 항목인지 이야기를 나눠보면 좋을 것 같습니다~

**Comment by pingpongworks** [comment]
시간이 많이 지나 상황이 달라졌습니다. 처리할 수 없는 '기증자에게만 전달 원함' 편지가 너무 많이 쌓이는 관계로 대여자 편지지에서 체크박스를 아예 없앴기 때문에 더이상 논의가 필요하다고 생각되지 않아 이슈 닫겠습니다. 쌓여있는 '기증자에게만 전달' 편지를 정리해야한다고 생각될 때 다시 정리해서 말씀드리겠습니다.
