### ISSUE TITLE
감사 이야기에서 대여 항목과 대여자 표시 방법 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#6]
![5](https://cloud.githubusercontent.com/assets/17288038/13104199/02f656c2-d59f-11e5-8a0a-ecfe73e15770.png)

## 대여자들이 이민우 님께 보내는 감사 이야기
재킷, 바지 대여자 - 장준석 님
재킷,바지 대여자 - 송상혁 님 
구두 대여자 - 손민석 님

**Comment by keedi** [comment]
진행합니다. 관련해서 갱신된 내용이 있다면 추가 바랍니다. :)

**Comment by keedi** [comment]
작업 완료했습니다. 릴리스 대기중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

문제없는지 확인해주시고 문제 없다면 **확인요망** 라벨 제거 부탁드립니다. :)
