### ISSUE TITLE
응원 이야기에서 기증 항목과 기증자 표시 방법 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#7]
![6](https://cloud.githubusercontent.com/assets/17288038/13104228/29620888-d59f-11e5-8149-fe4fba471fcb.png)
## 기증자들이 김남욱 님에게 보내는 응원 이야기
바지, 재킷 기증자 - 백운장 님
넥타이 기증자 - 김규철 님

**Comment by keedi** [comment]
진행합니다. 관련해서 갱신된 내용이 있다면 추가 바랍니다. :)

**Comment by keedi** [comment]
#6 이슈와 다르게 이쪽은 "... 님께 ..."가 아니라 "... 님에게 ..."라는 표현을 사용하고 있습니다. "님" 자체가 존칭인데 호응되는 접미사로는 "...에게" 보다는 "...께"가 적절한 것이 아닌가 싶어 확인차 남깁니다. 이슈에 남겨주신 그대로 진행할까요, 아니면 수정할까요?

**Comment by pingpongworks** [comment]
마찬가지로 '에게'로 통일부탁드려요. 저희 기증자나, 대여자 모두 젊은 층인데 '께'는 너무 무거운거 같아서요~^^

**Comment by keedi** [comment]
작업 완료했습니다. 릴리스 대기중입니다.

**Comment by keedi** [comment]
릴리스 및 배포 완료했습니다.

문제없는지 확인해주시고 문제 없다면 **확인요망** 라벨 제거 부탁드립니다. :)
