### ISSUE TITLE
대여 주문확정 후 발송되는 문자메시지에 이야기옷장 안내를 추가하고자 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Story-Web#9]
[열린옷장] 이성일님 안녕하세요. 택배반납을 하시거나 연장신청이 필요한 경우, 본 문자를 보관하고 계시다가 반드시 아래 주소를 클릭하여 정보를 입력해주세요. 정보 미입력시 미반납, 연체 상황이 발생할 수 있으므로 반드시 본 정보 작성을 요청드립니다. 감사합니다.

1.택배로 발송을 하신 경우: http://staff.theopencloset.net/order/19953/return 를 클릭하여 반납택배 발송알리미를 작성해주세요.

2.대여기간을 연장하려는 경우: http://staff.theopencloset.net/order/19953/extension 를 클릭하여 대여기간 연장신청서를 작성해주세요.

3.기증이야기 안내 : https://story.theopencloset.net/letters/o/22852/d 를 클릭하시어 오늘 대여하신 의류의 기증이야기를 만나보세요.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/784에 적어 놓았습니다.
